// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvwdjqxyxivejtuhigxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2d2RqcXh5eGl2ZWp0dWhpZ3hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MTMwNzMsImV4cCI6MjA2Njk4OTA3M30.c4U9k1iO9PH7Q_Wq7BBvFTnoOga69S4Zw0kOgscFw-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});